language: node_js

node_js:
- "10"

mono:
  - latest

env:
- CODE_VERSION=1.45.0

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      Xvfb :99 &
      sleep 3;
    fi
  - dpkg --compare-versions `npm -v` ge 6.7 || npm i -g npm@^6.7
  - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-3.1
  - sudo apt install xvfb

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - libsecret-1-dev

install:
- npm ci
- npm i -g gulp
- gulp 'vsix:release:package'

script:
  - gulp cov:instrument
  - gulp test
  - gulp cov:report
  - npm run test:artifacts
  - 'if [[ "$TRAVIS_BRANCH" != "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then npm run test:release; fi'

after_failure:
  - ./.travis/printLogs.sh

after_success:
  - ./.travis/printLogs.sh
