name: OmniSharp-VSCode CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup virtual display
      run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Install .NET Core 3.1 SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x

    - name: Install Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    - name: Install dependencies
      run: |
          npm ci
          npm i -g gulp

    - name: Compile
      run: npm run compile

    - name: Build extension package
      run: gulp 'vsix:release:package'

    - name: Run unit and integration tests
      run: |
          gulp cov:instrument
          gulp test
          gulp cov:merge
          npm run test:artifacts
      env:
        CODE_VERSION: 1.45.0
        DISPLAY: :99.0

    - name: Report unit test coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/unit/lcov.info
        flags: unit

    - name: Report integration test coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/integration/lcov.info
        flags: integration

    - name: Run artifact tests
      run: npm run test:artifacts

    - name: Upload VSIX build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ci-extension-artifact
        path: ./*.vsix
