name: OmniSharp-VSCode CI

on:
  push:
    branches: [ master, feature/** ]

  pull_request:
    branches: [ master, feature/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    - name: Install .NET Core 7.x SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 7.x

    - name: Install Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
          npm ci
          npm i -g gulp

    - name: Compile
      run: npm run compile

    - name: Prepublish VSIX
      run: npm run vscode:prepublish

    - name: Build platform-specific extension packages
      run: gulp 'vsix:release:package'

    - name: Upload VSIX build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ci-extension-artifact
        path: ./*.vsix
